name: QuoteApp
description: easy quote
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1
environment:
  sdk: ">=2.18.0 <=4.0.1"
dependencies:
  flutter:
    sdk: flutter

  # firebase services
  firebase_auth: ^5.3.3
  cloud_firestore: ^5.5.0
  firebase_core: ^3.8.0
  cloud_functions: ^5.1.5
  firebase_storage: ^12.3.6
  # Cupertino Icons and font
  cupertino_icons: ^1.0.3
  # state
  provider: ^6.1.2
  # save file
  path_provider: ^2.0.6
  # format dates
  intl: ^0.17.0
  # take image
  image_picker: ^0.8.5+3
  # check permission
  permission_handler: ^8.2.6
  # hive for local database
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  # alert
  awesome_dialog: ^3.2.1
  # url_launcher
  url_launcher: ^6.1.5
  # fonts
  google_fonts: ^4.0.0
  # splash screen
  flutter_native_splash: ^2.3.8
  # animations
  animated_bottom_navigation_bar: ^1.3.3
  page_transition: ^2.1.0
  flutter_card_swiper: ^7.0.2
  lottie: ^3.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  hive_generator: ^1.1.1
  build_runner: ^2.1.5

flutter_native_splash:
  color: "#ffffff"
  image: assets/images/splash.png
  android: true
  ios: true

# The following section is specific to Flutter.
flutter:
  disable-swift-package-manager: true
  uses-material-design: true
  assets:
    - assets/fonts/VarelaRound-Regular.ttf
    - assets/fonts/ArialUnicodeMS.ttf
    - assets/fonts/OpenSans-Bold.ttf
    - assets/fonts/OpenSans-Regular.ttf
    - assets/images/login_wallpaper.jpeg
    - assets/animations/empty.json
    - assets/animations/loading.json
    - assets/animations/data_not_found.json
    - assets/animations/error.json
    - assets/animations/small_error.json
    - assets/images/
